{{- if .Values.ingress.enable -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{- else }}
  namespace: default
{{- end }}
  name: {{ template "traefik.fullname" . }}
  labels: 
    app: {{ template "traefik.fullname" . }}
  {{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      # - path: /*
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: ssl-redirect
      #       port:
      #         number: use-annotation
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: {{ template "traefik.fullname" . }}
            port: 
              number: 80
{{- end }}
