{{- if .Values.ingress.enable -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{- else }}
  namespace: default
{{- end }}
  name: {{ template "traefik.fullname" . }}
  labels: 
    app: {{ template "traefik.fullname" . }}
  {{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: {{ template "traefik.fullname" . }}
              servicePort: 80
{{- end }}
